[project]
version = "0.1.0"
name = "doublelist"
description = "A doubly linked list suitable for stack allocation."
cincludes = []
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
err = "*"
log = "*"
mem = "*"
